
name: Deploy package

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: docker://clojure:tools-deps
      - uses: actions/checkout@v2

      - name: Cache Clojars
        uses: actions/cache@v1
        env:
          cache-name: cache-clojars
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('shadow-cljs.edn') }}
          restore-keys: |
            ${{ runner.os }}-clojars

      - name: run tests
        run: 'yarn && yarn shadow-cljs compile test-only && node ./target/test.js'

      - name: deploy to clojars
        run: env CLOJARS_USERNAME=username CLOJARS_PASSWORD=${{ secrets.CLOJARS_PASSWORD }} clojure -A:depstar && clojure -A:deploy
